[workspace]
authors = ["mpeschek <michaelpeschek@icloud.com>"]
channels = ["conda-forge"]
name = "diabetes_prediction_challenge"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pandas = ">=2.3.3,<3"
scikit-learn = ">=1.7.2,<2"
xgboost = ">=3.1.2,<4"
catboost = ">=1.2.8,<2"
